### ISSUE TITLE
[CLI][BUG] Quiet mode not working

### ISSUE THREAD

**Issue by alsastre** [fernandezvara/certsfor#28]
When listing certificates:
`./cfd --config ~/cfdconfig.yml list certificates --csv`

With either `--quiet` or with `export CFD_QUIET=true`

The following information appears on the output:
```
./cfd  list certificates --csv --quiet 
badger 2021/02/06 14:14:50 INFO: All 1 tables opened in 0s
badger 2021/02/06 14:14:50 INFO: Replaying file id: 0 at offset: 100921
badger 2021/02/06 14:14:50 INFO: Replay took: 5.423µs
badger 2021/02/06 14:14:50 DEBUG: Value log discard stats empty
Common Name,Distinguished Name,Expires in
...
```

**Comment by alsastre** [comment]
This mode was working on `0.1.11`

**Comment by fernandezvara** [comment]
Badger logger logs to the error out, while data is written to the standard out, so redirecting to a file will work.

The issue here is leverage the badger driver logging itself
